import pytest
from unittest.mock import AsyncMock, MagicMock, patch

from wiki.models.module_tree import ModuleNode, ModuleTree


@pytest.mark.asyncio
async def test_compose_bottomup_generates_pages():
    from wiki.nodes.graph_nodes import compose_bottomup_node

    state = {
        "business_id": "test",
        "repositories": ["repo1"],
        "modules": {"repo1": []},
        "module_tree": [
            {
                "canonical_key": "root",
                "entity_uids": ["u1", "u2"],
                "file_paths": ["a.py", "b.py"],
                "title": "Root Module",
                "description": "",
                "token_estimate": 1000,
                "children": [
                    {
                        "canonical_key": "leaf-a",
                        "entity_uids": ["u1"],
                        "file_paths": ["a.py"],
                        "title": "Leaf A",
                        "description": "",
                        "token_estimate": 500,
                        "children": [],
                    },
                ],
            },
        ],
        "canonical_keys": {"root": "Root Module", "leaf-a": "Leaf A"},
        "domain_cache": {},
        "pages": [],
        "config": {},
        "language": "zh",
        "errors": [],
    }

    mock_llm = AsyncMock()
    mock_llm.generate.return_value = "# Generated Content"
    config = {"configurable": {"llm": mock_llm}}

    result = await compose_bottomup_node(state, config)
    assert "pages" in result
    assert len(result["pages"]) >= 2  # leaf + parent


@pytest.mark.asyncio
async def test_compose_bottomup_with_parent_children():
    """When tree has parent-children structure, ParentSynthesizer should be called."""
    from wiki.nodes.graph_nodes import compose_bottomup_node

    mock_llm = AsyncMock()
    mock_llm.generate.return_value = "# Generated Content\n\nSome content."

    child1 = ModuleNode(
        canonical_key="child-1",
        entity_uids=["A"],
        file_paths=["src/a.py"],
        title="Child 1",
    )
    child2 = ModuleNode(
        canonical_key="child-2",
        entity_uids=["B"],
        file_paths=["src/b.py"],
        title="Child 2",
    )
    parent = ModuleNode(
        canonical_key="parent-mod",
        entity_uids=["A", "B"],
        file_paths=["src/a.py", "src/b.py"],
        title="Parent Module",
        children=[child1, child2],
    )
    tree = ModuleTree(roots=[parent], repo_id="test")

    state = {
        "module_tree": tree.to_dicts(),
        "business_id": "test",
        "domain_cache": {},
        "module_summaries": {},
        "pages": [],
    }
    config = {"configurable": {"llm": mock_llm}}

    result = await compose_bottomup_node(state, config)

    pages = result["pages"]
    assert len(pages) == 3
    page_keys = {p["canonical_key"] for p in pages}
    assert "child-1" in page_keys
    assert "child-2" in page_keys
    assert "parent-mod" in page_keys
    assert mock_llm.generate.call_count >= 3


@pytest.mark.asyncio
async def test_compose_leaf_uses_agent_when_graph_store_available():
    """When graph_store is in config, leaf generation should use WikiPageAgent."""
    mock_llm = AsyncMock()
    mock_llm.generate.return_value = "# Fallback\n\nFallback content."
    mock_graph_store = MagicMock()

    leaf = ModuleNode(
        canonical_key="leaf-mod",
        entity_uids=["FooService"],
        file_paths=["src/foo.py"],
        title="Foo Service",
    )
    tree = ModuleTree(roots=[leaf], repo_id="test")

    state = {
        "module_tree": tree.to_dicts(),
        "business_id": "test",
        "domain_cache": {},
        "module_summaries": {},
        "pages": [],
    }
    config = {
        "configurable": {
            "llm": mock_llm,
            "graph_store": mock_graph_store,
            "repo_path": "/tmp/test-repo",
        },
    }

    with patch("wiki.page_agent.WikiPageAgent") as MockAgent:
        mock_agent_instance = AsyncMock()
        mock_agent_instance.generate.return_value = (
            "# Foo Service\n\nGenerated by agent with code reading tools."
        )
        MockAgent.return_value = mock_agent_instance

        from wiki.nodes.graph_nodes import compose_bottomup_node

        result = await compose_bottomup_node(state, config)

    pages = result["pages"]
    assert len(pages) == 1
    assert (
        "agent" in pages[0]["content"].lower()
        or "Foo Service" in pages[0]["content"]
    )
    MockAgent.assert_called_once_with(
        llm=mock_llm,
        graph_store=mock_graph_store,
        repo_path="/tmp/test-repo",
    )
    mock_agent_instance.generate.assert_called_once()
