"""P6 — User-triggered wiki export to repository docs (preview + selective write)."""

from __future__ import annotations

from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Literal

from wiki.models import WikiPage

ExportAction = Literal["create", "update", "skip"]


@dataclass
class ExportDiff:
    file_path: str  # target file path in repository (wiki page path)
    action: ExportAction
    wiki_content: str
    repo_content: str | None
    diff_summary: str


@dataclass
class ExportResult:
    diffs: list[ExportDiff]
    total_files: int
    created: int
    updated: int
    skipped: int


def export_result_to_dict(result: ExportResult) -> dict[str, Any]:
    return {
        "diffs": [asdict(d) for d in result.diffs],
        "total_files": result.total_files,
        "created": result.created,
        "updated": result.updated,
        "skipped": result.skipped,
    }


class WikiDocsExporter:
    """Export cached wiki pages to markdown files under a target directory."""

    AUTO_GENERATED_MARKER = "<!-- AUTO-GENERATED BY KBS -->"

    def __init__(self, wiki_cache: Any | None = None, store: Any | None = None) -> None:
        self._cache = wiki_cache
        self._store = store

    def _get_wiki_pages(self, repository: str) -> list[WikiPage]:
        if self._cache is None:
            return []
        merged: dict[str, WikiPage] = {}
        for p in self._cache.list_pages_for_repository(repository):
            merged[p.path] = p
        for p in self._cache.get_auxiliary_pages(repository):
            merged[p.path] = p
        return list(merged.values())

    @staticmethod
    def _rel_posix(page_path: str) -> str:
        rel = page_path.replace("\\", "/").lstrip("/")
        if not rel:
            raise ValueError(f"Invalid wiki page path: {page_path!r}")
        for part in Path(rel).parts:
            if part == "..":
                raise ValueError(f"Invalid wiki page path: {page_path!r}")
        return rel

    @staticmethod
    def _safe_target_file(target_dir: str, page_path: str) -> Path:
        root = Path(target_dir).resolve()
        rel = WikiDocsExporter._rel_posix(page_path)
        full = (root / rel).resolve()
        try:
            full.relative_to(root)
        except ValueError as exc:
            raise ValueError(f"Path escapes target_dir: {page_path!r}") from exc
        return full

    def _wiki_blob(self, page: WikiPage, *, include_marker: bool) -> str:
        body = page.to_markdown()
        if include_marker:
            return f"{self.AUTO_GENERATED_MARKER}\n\n{body}"
        return body

    async def preview_export(
        self,
        repository: str,
        target_dir: str,
        *,
        include_auto_generated_marker: bool = True,
    ) -> ExportResult:
        """Generate diff preview without writing files."""
        pages = self._get_wiki_pages(repository)
        diffs: list[ExportDiff] = []
        created = 0
        updated = 0
        skipped = 0

        for page in pages:
            wiki_content = self._wiki_blob(page, include_marker=include_auto_generated_marker)
            target_file = self._safe_target_file(target_dir, page.path)

            if target_file.exists():
                existing = target_file.read_text(encoding="utf-8")
                if self.AUTO_GENERATED_MARKER not in existing:
                    diffs.append(
                        ExportDiff(
                            file_path=page.path,
                            action="skip",
                            wiki_content=wiki_content,
                            repo_content=existing,
                            diff_summary="Human-written file, skipped",
                        )
                    )
                    skipped += 1
                elif existing == wiki_content:
                    skipped += 1
                else:
                    diffs.append(
                        ExportDiff(
                            file_path=page.path,
                            action="update",
                            wiki_content=wiki_content,
                            repo_content=existing,
                            diff_summary="Content changed",
                        )
                    )
                    updated += 1
            else:
                diffs.append(
                    ExportDiff(
                        file_path=page.path,
                        action="create",
                        wiki_content=wiki_content,
                        repo_content=None,
                        diff_summary="New file",
                    )
                )
                created += 1

        return ExportResult(
            diffs=diffs,
            total_files=len(pages),
            created=created,
            updated=updated,
            skipped=skipped,
        )

    async def execute_export(
        self,
        repository: str,
        target_dir: str,
        *,
        selected_files: list[str] | None = None,
    ) -> ExportResult:
        """Write files for create/update entries; optionally restrict to ``selected_files``."""
        preview = await self.preview_export(repository, target_dir)
        selected_set = set(selected_files) if selected_files is not None else None
        to_write = [
            d
            for d in preview.diffs
            if d.action in ("create", "update")
            and (selected_set is None or d.file_path in selected_set)
        ]
        written_paths: set[str] = set()
        for d in to_write:
            path = self._safe_target_file(target_dir, d.file_path)
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(d.wiki_content, encoding="utf-8")
            written_paths.add(d.file_path)

        if not written_paths:
            return preview

        return await self.preview_export(repository, target_dir)
